spring:
  datasource:
    url: jdbc:h2:mem:testdb # h2 url ex_): jdbc:h2:tcp://localhost/~/test
    driver-class-name: org.h2.Driver
    username: sa # h2 id
    password: # h2 password
  h2:
    console:
      enabled: true

# RabbitMQ 설정
rabbitmq:
  host: "localhost"
  port: 5672
  virtual-host: "/"
  username: "guest"
  password: "guest"
  relay:
    port: 61613
    system-login: guest
    system-passcode: guest
    client-login: guest
    client-passcode: guest
  chat:
    queue:
      name: "chat.queue"
    exchange:
      name: "chat.exchange"
    routing:
      key: "*.room."

logging:
  level:
    org.springframework.messaging: trace
    org.springframework.web.socket: trace
